server.port=8080

# OpenAI API Key
openai.api.key=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